const crypto = require("../../utils/crypto");

const LIB_VERSIONS = {
    express: "^4.19.2", cors: "^2.8.5", dotenv: "^16.4.5", nodemon: "^3.1.0",
    mongoose: "^8.2.0", pg: "^8.11.3", sequelize: "^6.37.1", mysql2: "^3.9.2"
};

const generatePackageJson = (projectName, dbType, tables) => {
    const dependencies = {
        "express": LIB_VERSIONS.express,
        "cors": LIB_VERSIONS.cors,
        "dotenv": LIB_VERSIONS.dotenv,
    };
    const devDependencies = { "nodemon": LIB_VERSIONS.nodemon };

    // Auto-detect if we need hashing or UUID libraries based on the user's schema
    let needsBcrypt = false, needsArgon2 = false, needsUuid = false;
    tables.forEach(t => {
        t.fields.forEach(f => {
            if (f.isHashed) {
                if (f.hashAlgorithm === 'argon2') needsArgon2 = true;
                else needsBcrypt = true;
            }
            if (f.isUuid) needsUuid = true;
        });
    });

    if (needsBcrypt) dependencies["bcrypt"] = "^5.1.1";
    if (needsArgon2) dependencies["argon2"] = "^0.40.1";
    if (needsUuid) dependencies["uuid"] = "^10.0.0";

    if (dbType === 'postgresql') {
        dependencies["pg"] = LIB_VERSIONS.pg;
        dependencies["sequelize"] = LIB_VERSIONS.sequelize;
    } else if (dbType === 'mysql') {
        dependencies["mysql2"] = LIB_VERSIONS.mysql2;
        dependencies["sequelize"] = LIB_VERSIONS.sequelize;
    } else if (dbType === 'mongodb') {
        dependencies["mongoose"] = LIB_VERSIONS.mongoose;
    }

    return JSON.stringify({
        name: projectName.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
        version: "1.0.0",
        description: "Generated by DragEnd",
        main: "server.js",
        scripts: { "start": "node server.js", "dev": "nodemon server.js" },
        dependencies,
        devDependencies
    }, null, 2);
};

const generateDotEnv = (port, dbType, dbConfig, dbName) => {
    let envContent = `PORT=${port}\n`;
    if (!dbConfig) return envContent + `# DB Config Missing`;

    const creds = dbConfig.credentials || {};
    let password = creds.password;
    try { password = crypto.decrypt(creds.password); } catch (e) { }
    const databaseName = dbName || 'myapp';

    if (dbType === 'mongodb') {
        const uri = dbConfig.uri || `mongodb://${creds.host || 'localhost'}:${creds.port || 27017}/${databaseName}`;
        envContent += `MONGO_URI=${uri}\n`;
    } else {
        envContent += `DB_HOST=${creds.host || 'localhost'}\n`;
        envContent += `DB_PORT=${creds.port || 3306}\n`;
        envContent += `DB_USER=${creds.username || 'root'}\n`;
        envContent += `DB_PASS=${password || ''}\n`;
        envContent += `DB_NAME=${databaseName}\n`;
        envContent += `DB_DIALECT=${dbType === 'postgresql' ? 'postgres' : 'mysql'}\n`;
    }
    return envContent;
};

const generateServerJs = (port, dbType) => {
    const dbImport = dbType === 'mongodb'
        ? `const connectDB = require('./models/index');`
        : `const { connectDB } = require('./models/index');`;

    return `const express = require('express');
const app = express();
const cors = require('cors');
require('dotenv').config();
const routes = require('./routes'); 
${dbImport}

const PORT = process.env.PORT || ${port};

// Middleware
app.use(cors());
app.use(express.json());

// Database Connection
connectDB();

// Routes
app.use('/api', routes); // Mounts all routes under /api

// Start Server
app.listen(PORT, () => {
  console.log(\`Server running on: http://localhost:\${PORT}\`);
});
`;
};


const generateDbConnection = (dbType, tableNames) => {
    if (dbType === 'mongodb') {
        return `const mongoose = require('mongoose');

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB Connected Successfully");
  } catch (err) {
    console.error("MongoDB Connection Error:", err.message);
    process.exit(1);
  }
};

module.exports = connectDB;`;
    } else {
        const modelImports = tableNames.map(name =>
            `db.${name} = require('./${name}')(sequelize, DataTypes);`
        ).join('\n');

        return `const { Sequelize, DataTypes } = require('sequelize');

const sequelize = new Sequelize(
  process.env.DB_NAME,
  process.env.DB_USER,
  process.env.DB_PASS,
  {
    host: process.env.DB_HOST,
    dialect: process.env.DB_DIALECT,
    port: process.env.DB_PORT,
    logging: false
  }
);

const db = {};
db.Sequelize = Sequelize;
db.sequelize = sequelize;

// Import Models
${modelImports}

// Connection Function
db.connectDB = async () => {
  try {
    await sequelize.authenticate();
    console.log('Database Connected...');
    await sequelize.sync({ alter: true }); 
    console.log('Tables Synced...');
  } catch (err) {
    console.error('Error: ' + err);
  }
};

module.exports = db;`;
    }
};

const generateModelFile = (table, dbType) => {
    // --- MONGODB GENERATION ---
    if (dbType === 'mongodb') {
        let fieldsArr = [];
        table.fields.forEach(f => {
            let typeStr = f.type === 'number' ? 'Number' : f.type === 'boolean' ? 'Boolean' : f.type === 'date' ? 'Date' : f.type === 'json' ? 'mongoose.Schema.Types.Mixed' : 'String';
            if (f.constraint === 'foreign' && f.targetTable) typeStr = 'mongoose.Schema.Types.ObjectId';
            if (f.isUuid) typeStr = 'String';

            let props = [`type: ${f.isArray ? `[${typeStr}]` : typeStr}`];
            if (f.required) props.push(`required: true`);
            if (f.unique || f.index) props.push(`unique: true`);
            if (f.constraint === 'foreign' && f.targetTable) props.push(`ref: '${f.targetTable}'`);
            if (f.defaultValue) props.push(`default: ${f.type === 'string' ? `'${f.defaultValue}'` : f.defaultValue}`);
            if (f.isHidden) props.push(`select: false`);

            // Validations
            if (f.type === 'string' && f.minLength) props.push(`minlength: ${f.minLength}`);
            if (f.type === 'string' && f.maxLength) props.push(`maxlength: ${f.maxLength}`);
            if (f.type === 'string' && f.regexPattern) props.push(`match: /${f.regexPattern}/`);
            if (f.type === 'number' && f.minValue) props.push(`min: ${f.minValue}`);
            if (f.type === 'number' && f.maxValue) props.push(`max: ${f.maxValue}`);
            if (f.type === 'enum' && f.enumValues) props.push(`enum: [${f.enumValues.split(',').map(e => `'${e.trim()}'`).join(', ')}]`);

            fieldsArr.push(`  ${f.name}: { ${props.join(', ')} }`);
        });

        let imports = `const mongoose = require('mongoose');\n`;
        let hooks = '';

        const hashedFields = table.fields.filter(f => f.isHashed);
        const uuidFields = table.fields.filter(f => f.isUuid && f.constraint === 'primary');

        if (hashedFields.length > 0 || uuidFields.length > 0) {
            if (hashedFields.some(f => f.hashAlgorithm === 'bcrypt')) imports += `const bcrypt = require('bcrypt');\n`;
            if (hashedFields.some(f => f.hashAlgorithm === 'argon2')) imports += `const argon2 = require('argon2');\n`;
            if (hashedFields.some(f => f.hashAlgorithm === 'sha256')) imports += `const crypto = require('crypto');\n`;
            if (uuidFields.length > 0) imports += `const { v4: uuidv4 } = require('uuid');\n`;

            hooks += `\n${table.name}Schema.pre('save', async function(next) {\n`;

            uuidFields.forEach(f => {
                hooks += `  if (this.isNew && !this.${f.name}) this.${f.name} = uuidv4();\n`;
            });

            hashedFields.forEach(f => {
                hooks += `  if (this.isModified('${f.name}')) {\n`;
                if (f.hashAlgorithm === 'argon2') hooks += `    this.${f.name} = await argon2.hash(this.${f.name});\n`;
                else if (f.hashAlgorithm === 'sha256') hooks += `    this.${f.name} = crypto.createHash('sha256').update(this.${f.name}).digest('hex');\n`;
                else hooks += `    this.${f.name} = await bcrypt.hash(this.${f.name}, 10);\n`;
                hooks += `  }\n`;
            });
            hooks += `  next();\n});\n`;
        }

        return `${imports}\nconst ${table.name}Schema = new mongoose.Schema({\n${fieldsArr.join(',\n')}\n}, { timestamps: ${table.timestamps ? 'true' : 'false'} });\n${hooks}\nmodule.exports = mongoose.model('${table.name}', ${table.name}Schema);`;
    }

    // --- SQL / SEQUELIZE GENERATION ---
    else {
        let fieldsArr = [];
        table.fields.forEach(f => {
            let typeStr = f.isUuid ? 'DataTypes.UUID' : f.type === 'number' ? 'DataTypes.INTEGER' : f.type === 'boolean' ? 'DataTypes.BOOLEAN' : f.type === 'date' ? 'DataTypes.DATE' : f.type === 'json' ? 'DataTypes.JSON' : 'DataTypes.STRING';
            if (f.type === 'enum' && f.enumValues) typeStr = `DataTypes.ENUM(${f.enumValues.split(',').map(e => `'${e.trim()}'`).join(', ')})`;

            let props = [`type: ${typeStr}`];
            if (f.constraint === 'primary') props.push(`primaryKey: true`);
            if (f.isUuid && f.constraint === 'primary') props.push(`defaultValue: DataTypes.UUIDV4`);
            if (f.autoIncrement && f.constraint === 'primary') props.push(`autoIncrement: true`);

            props.push(`allowNull: ${!f.required}`);
            if (f.unique) props.push(`unique: true`);
            if (f.defaultValue) props.push(`defaultValue: ${f.type === 'string' ? `'${f.defaultValue}'` : f.defaultValue}`);

            if (f.constraint === 'foreign' && f.targetTable) {
                props.push(`references: { model: '${f.targetTable}', key: '${f.targetField || 'id'}' }`);
                if (f.onDelete) props.push(`onDelete: '${f.onDelete.toUpperCase()}'`);
                if (f.onUpdate) props.push(`onUpdate: '${f.onUpdate.toUpperCase()}'`);
            }

            let validate = [];
            if (f.minLength || f.maxLength) validate.push(`len: [${f.minLength || 0}, ${f.maxLength || 255}]`);
            if (f.regexPattern) validate.push(`is: /${f.regexPattern}/`);
            if (f.minValue) validate.push(`min: ${f.minValue}`);
            if (f.maxValue) validate.push(`max: ${f.maxValue}`);
            if (validate.length > 0) props.push(`validate: { ${validate.join(', ')} }`);

            fieldsArr.push(`    ${f.name}: { ${props.join(', ')} }`);
        });

        let imports = '', hooks = '';
        const hashedFields = table.fields.filter(f => f.isHashed);
        if (hashedFields.length > 0) {
            if (hashedFields.some(f => f.hashAlgorithm === 'bcrypt')) imports += `const bcrypt = require('bcrypt');\n`;
            if (hashedFields.some(f => f.hashAlgorithm === 'argon2')) imports += `const argon2 = require('argon2');\n`;
            if (hashedFields.some(f => f.hashAlgorithm === 'sha256')) imports += `const crypto = require('crypto');\n`;

            const hookLogic = (instanceVar, isUpdate) => {
                let logic = '';
                hashedFields.forEach(f => {
                    const condition = isUpdate ? `if (${instanceVar}.changed('${f.name}')) {` : `if (${instanceVar}.${f.name}) {`;
                    let hashLine = f.hashAlgorithm === 'argon2' ? `await argon2.hash(${instanceVar}.${f.name})` : f.hashAlgorithm === 'sha256' ? `crypto.createHash('sha256').update(${instanceVar}.${f.name}).digest('hex')` : `await bcrypt.hash(${instanceVar}.${f.name}, 10)`;
                    logic += `      ${condition} ${instanceVar}.${f.name} = ${hashLine}; }\n`;
                });
                return logic;
            };

            hooks += `\n  ${table.name}.beforeCreate(async (user) => {\n${hookLogic('user', false)}  });`;
            hooks += `\n  ${table.name}.beforeUpdate(async (user) => {\n${hookLogic('user', true)}  });`;
        }

        return `${imports}module.exports = (sequelize, DataTypes) => {\n  const ${table.name} = sequelize.define('${table.name}', {\n${fieldsArr.join(',\n')}\n  }, { timestamps: ${table.timestamps ? 'true' : 'false'} });\n${hooks}\n  return ${table.name};\n};`;
    }
};

const generateController = (tableName, endpoints, dbType) => {
    const modelName = tableName;

    let code = dbType === 'mongodb'
        ? `const ${modelName} = require('../models/${modelName}');\n\n`
        : `const db = require('../models');\nconst ${modelName} = db.${modelName};\n\n`;

    endpoints.forEach(ep => {
        const funcName = ep.route.replace(/^\//, '').replace(/[^a-zA-Z0-9]/g, '');

        code += `exports.${funcName} = async (req, res) => {\n`;
        code += `  try {\n`;

        if (ep.method === 'GET') {
            const select = ep.selectedFields && ep.selectedFields.length > 0
                ? (dbType === 'mongodb' ? `.select('${ep.selectedFields.join(' ')}')` : `, { attributes: [${ep.selectedFields.map(f => `'${f}'`).join(',')}] }`)
                : '';

            if (dbType === 'mongodb') {
                code += `    const data = await ${modelName}.find({})${select};\n`;
            } else {
                code += `    const data = await ${modelName}.findAll(${select ? select.substring(2) : ''});\n`;
            }
            code += `    res.status(200).json(data);\n`;

        } else if (ep.method === 'POST') {
            code += `    const newData = await ${modelName}.create(req.body);\n`;
            code += `    res.status(201).json(newData);\n`;

        } else if (ep.method === 'PUT') {
            code += `    // Update logic here\n`;
            code += `    res.status(200).json({ msg: "Update endpoint hit" });\n`;
        } else if (ep.method === 'DELETE') {
            code += `    // Delete logic here\n`;
            code += `    res.status(200).json({ msg: "Delete endpoint hit" });\n`;
        }

        code += `  } catch (err) {\n`;
        code += `    res.status(500).json({ error: err.message });\n`;
        code += `  }\n`;
        code += `};\n\n`;
    });

    return code;
}

const generateRouteFile = (controllerName, endpoints) => {
    let code = `const express = require('express');\n`;
    code += `const router = express.Router();\n`;
    code += `const controller = require('../controllers/${controllerName}');\n\n`;

    endpoints.forEach(ep => {
        const funcName = ep.route.replace(/^\//, '').replace(/[^a-zA-Z0-9]/g, '');
        const routePath = ep.route.startsWith('/') ? ep.route : `/${ep.route}`;
        code += `router.${ep.method.toLowerCase()}('${routePath}', controller.${funcName});\n`;
    });

    code += `\nmodule.exports = router;`;
    return code;
};
exports.generateExpressProject = (zip, data) => {
    const { project, dbType, dbConfig, dbName, tables, groupedEndpoints } = data;

    zip.file("package.json", generatePackageJson(project.name, dbType, tables));
    zip.file(".env", generateDotEnv(8080, dbType, dbConfig, dbName));
    zip.file("server.js", generateServerJs(8080, dbType));
    zip.file("README.md", `# ${project.name}\nGenerated Express Project\n\nRun:\n\`npm install\`\n\`npm run dev\``);

    const modelsFolder = zip.folder("models");
    const tableNames = tables.map(t => t.name);
    modelsFolder.file("index.js", generateDbConnection(dbType, tableNames));

    tables.forEach(table => {
        modelsFolder.file(`${table.name}.js`, generateModelFile(table, dbType));
    });

    const controllersFolder = zip.folder("controllers");
    const routesFolder = zip.folder("routes");
    let routesIndexContent = `const router = require('express').Router();\n\n`;

    Object.keys(groupedEndpoints).forEach(tableName => {
        const groupEndpoints = groupedEndpoints[tableName];
        const controllerName = `${tableName}Controller`;

        controllersFolder.file(`${controllerName}.js`, generateController(tableName, groupEndpoints, dbType));
        routesFolder.file(`${tableName}.js`, generateRouteFile(controllerName, groupEndpoints));

        routesIndexContent += `const ${tableName}Routes = require('./${tableName}');\n`;
        routesIndexContent += `router.use('/${tableName.toLowerCase()}', ${tableName}Routes);\n`;
    });

    routesIndexContent += `\nmodule.exports = router;`;
    routesFolder.file("index.js", routesIndexContent);
};